name: Commit changes
description: Commit changes to the repository

inputs:
  commit_message:
    description: Commit message for changes to be pushed
    required: false
    default: "${{ github.job }} job pushed changes"
  file_path:
    description: File / Folder to add for commit
    required: false
    default: "."
outputs:
  commit_executed:
    description: Indicates whether a commit was executed
    value: ${{ steps.commit-changes.outputs.commit_executed }}

runs:
  using: "composite"
  steps:
    - name: Commit changes
      id: commit-changes
      shell: bash
      run: ${{ github.action_path }}/git-commit.sh
      env:
        commit_message: ${{ inputs.commit_message }}
        file_path: ${{ inputs.file_path }}
