name: Calculate repository size
description: Calculate the repository size and store the result in a YAML file

inputs:
  repo_size_file:
    description: Path to the file where repo sizes will be stored
    required: false
    default: .github/repo-size.yaml

runs:
  using: composite
  steps:
    - name: Calculate repository size
      shell: bash
      run: ${{ github.action_path }}/repo-size.sh
      env:
        repo_size_file: ${{ inputs.repo_size_file }}

    - name: Print the repo sizes data file
      shell: bash
      run: cat ${{ inputs.repo_size_file }}
