name: Configure git
description: Configures git username and useremail config variables.

inputs:
  user_name:
    description: Git user name
    required: true
    default: github-actions[bot]
  user_email:
    description: Git user email
    required: true
    default: 41898282+github-actions[bot]@users.noreply.github.com

runs:
  using: composite
  steps:
    - name: Configure git
      shell: bash
      run: git/configure/git-configure.sh
      env:
        user_name: ${{ inputs.user_name }}
        user_email: ${{ inputs.user_email }}
