name: Checkout Branch
description: Checkout and switch to a branch in the repository

inputs:
  branch_name:
    description: Branch name to checkout and switch to
    required: false
    default: main

runs:
  using: composite
  steps:
    - name: Checkout branch
      shell: bash
      run: ${{ github.action_path }}/git-checkout-branch.sh
      env:
        branch_name: ${{ inputs.branch_name }}
