name: Checkout Branch
description: Checkout and switch to a branch in the repository

inputs:
  branch_name:
    description: Branch name to checkout and switch to
    required: false
    default: main

runs:
  using: composite
  steps:
    - name: Checkout branch
      shell: bash
      run: |
        # Check if the branch name is empty string
        if [ -z "${{ inputs.branch_name }}" ]; then
          echo "Branch name is provided empty string. Using default branch 'main'."
          branch_name="main"
        else
          branch_name="${{ inputs.branch_name }}"
        fi
        # Checkout the specified branch
        git checkout -B "$branch_name"
